### ISSUE TITLE
feat: provide details when parsing fails

### ISSUE THREAD

**Issue by taroball01** [taroball01/miniob_shell#4]
Currently it only prints a line shows that parsing fails, and only provide unknow character info.
Need more information when other error occurs.

**Comment by tar-op** [comment]
There are 2 places where emit errors about parsing currently:
| Error Type | From |
|--------|--------|
| Unknown Character | Parser |
| Unexpected Token | Parser |
| Mismatched Type  | Preprocessor |
| Unknown Attribute | Preprocessor |
| Unknown Relation | Preprocessor |
| Ambiguous Attribute | Preprocessor|

**Comment by tar-op** [comment]
Expected Parser Info output (take unknown character as example):
```
------| select * from @student;
------| ______________^
Parse Failed: Unknown Character '@'
```
------------------------------------
Thus if we want to show in this way, we need :
1. position where error occurs, e.g. [line, col]
2. input string that line. 
3. Error Type and Details

**Comment by tar-op** [comment]
**Brainstorm for this feature**

Which part output error message?
> Let `output_printer` do this, since we have done a similar but simpler function in it.

How to get position?
> * In Parser we can simply define YY_USER_ACTION and toggle on location option. 
> * In preprocessor, noticed that a lovely method `to_string` is provided, we can use this to compare with input string.

How to get Input string?
> * Transfer Input string to `output_printer`
> * When error occured, we can construct a `ParserErrorInfo` object as output, then pass it to `output_printer`.

**Comment by tar-op** [comment]
**Addition for output_printer:**
```cpp
class output_printer {
private:
   std::string sql_;
public:
  auto set_sql(const std::string& str);
  auto output_parser_error(ParserErrorInfo& info);
};
```

**ParserErrorInfo Interface**
```cpp
class ParserErrorInfo {
public:
  static auto match_raw(const std::string& str, int line) -> std::string;
  virtual auto get_position() -> pair<int,int> = 0;
  virtual auto get_raw_string() -> std::string = 0;
  virtual auto get_error_type() const -> ParserErrorType = 0;
  virtual auto get_details() const -> std::string = 0;
};
```

Once parser or preprocess failed due to parsing:
* ~~For parser, it will cause return-value of `sql_parse` to non-zero~~
* ~~For preprocessor, it will throw runtime_error~~
Better to throw and we can handle it all together
